import fs from 'node:fs';
import path from 'node:path';
import { Type } from '@mariozechner/pi-ai';
import { defineTool, type ExtensionAPI } from '@mariozechner/pi-coding-agent';
import { validateExtensionProject } from './validator';
import { runDeterministicInstall, type InstallResult } from './installer';
import type { ValidationResult } from './types';

import { normalizeMode, normalizeStage, inferKindFromGoal, type Mode, type Stage } from './router';
import { buildPlan } from './planner';
import { chooseNextAction, renderPayload, type ToolPayload, type DocumentationGuidance } from './renderer';
import { generateDocumentation } from './documenter';

interface ToolParams {
  mode?: string;
  stage?: string;
  goal?: string;
  extensionKind?: string;
  path?: string;
  sourcePath?: string;
  installTarget?: string;
  strict?: boolean;
  note?: string;
}



const extensionCreatorTool = defineTool({
  name: 'extension_creator',
  label: 'extension-creator',
  description: 'Plan, scaffold, review, validate, and route pi extension lifecycle actions.',
  parameters: Type.Object({
    mode: Type.Optional(
      Type.String({
        description: 'plan | scaffold | review | document | validate | install | update | remove',
      }),
    ),
    stage: Type.Optional(
      Type.String({
        description: 'idea | draft | workspace | validated | installed | maintenance | unknown',
      }),
    ),
    goal: Type.Optional(Type.String({ description: 'What the user wants the extension to do.' })),
    extensionKind: Type.Optional(Type.String({ description: 'The extension style, such as tool, command, prompt, or provider.' })),
    path: Type.Optional(Type.String({ description: 'Path to an external workspace or extension package.' })),
    sourcePath: Type.Optional(Type.String({ description: 'Source path (alias for path).' })),
    installTarget: Type.Optional(Type.String({ description: 'Optional install target or discovery preference.' })),
    strict: Type.Optional(Type.Boolean({ description: 'Prefer stricter cleanup and validation guidance.' })),
    note: Type.Optional(Type.String({ description: 'Additional instruction or context.' })),
  }),
  async execute(_toolCallId: string, params: ToolParams, signal: any, _onUpdate: any, ctx: any) {
    const goal = params.goal?.trim();
    const stage = normalizeStage(params.stage, goal, params.path);
    const mode = normalizeMode(params.mode, stage, goal, params.path);
    const strict = Boolean(params.strict);
    const extensionKind = params.extensionKind?.trim() || inferKindFromGoal(goal) || 'tool extension';
    const sourcePath = params.sourcePath?.trim() || params.path?.trim();
    const installTarget = params.installTarget?.trim();
    const note = params.note?.trim();

    let validation: ValidationResult | undefined;
    if ((mode === 'validate' || mode === 'review' || mode === 'install' || mode === 'update') && sourcePath) {
      validation = await validateExtensionProject(sourcePath);
    }

    const plan = mode === 'plan' || mode === 'scaffold'
      ? buildPlan({ goal, extensionKind, strict, note })
      : undefined;

    const installResult = mode === 'install' && sourcePath
      ? runDeterministicInstall({ sourcePath, validation })
      : undefined;

    // Notify user to reload pi after successful install
    if (installResult?.success) {
      ctx.ui?.notify?.('Extension installed. Restart pi to reload the new code!', 'info');
    }

    let documentation: DocumentationGuidance | undefined;
    if (mode === 'document' && sourcePath) {
      try {
        const generated = await generateDocumentation(sourcePath);
        documentation = {
          title: `Documentation for ${extensionKind}`,
          instruction: 'Generated by analyzing the extension source code.',
          promptTemplate: 'prompts/documentation.md',
          outputFiles: generated.filesWritten,
          steps: [
            `Wrote ${generated.filesWritten.join(', ')} to ${sourcePath}`,
            ...generated.filesWritten.map(f => `- ${f}: generated`),
          ],
        };

        // Actually write the files
        const readmePath = path.join(sourcePath, 'README.md');
        fs.writeFileSync(readmePath, generated.readme);

        if (generated.architecture) {
          const archPath = path.join(sourcePath, 'ARCHITECTURE.md');
          fs.writeFileSync(archPath, generated.architecture);
        }
      } catch (error) {
        documentation = {
          title: `Documentation for ${extensionKind}`,
          instruction: `Failed to generate documentation: ${error instanceof Error ? error.message : String(error)}`,
          promptTemplate: 'prompts/documentation.md',
          outputFiles: [],
          steps: ['Fix the error and re-run document mode.'],
        };
      }
    }

    const payload: ToolPayload = {
      mode,
      stage,
      startMode: mode,
      goal,
      extensionKind,
      sourcePath,
      installTarget,
      strict,
      note,
      validation,
      installResult,
      plan,
      documentation,
      nextAction: chooseNextAction({ mode, stage, sourcePath, validation, installResult, startMode: mode }),
    };

    if (!sourcePath && ['validate', 'review', 'install', 'update', 'remove'].includes(mode)) {
      payload.nextAction = 'Provide a source workspace path so pi can target the package source.';
    }

    ctx.ui?.notify?.('extension-creator tool completed', 'info');

    return {
      content: [{ type: 'text', text: renderPayload(payload) }],
      details: payload,
    };
  },
});

export default function extensionCreator(pi: ExtensionAPI) {
  pi.registerTool(extensionCreatorTool);
}